spring.application.name=Spring-Boot-Json
server.port=8080
app.ftp.version=100
app.ftp.port=80
app.ftp.username=arjun
app.ftp.password=pwd
server.error.include-message=always
server.error.include-stacktrace=always
management.endpoints.web.exposure.include=*
